language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://metaclass.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "JHAR871DCj83xGMQzdF/b4Q2ZA47hbRfekwcgcdE1EESh05wR1L/EO8CdpYIk9loastVAkHoBpJbG9SvcqDROLJyIndxlPqH2fFyulnL5IMMuNMPVNyOP5k4nlRzXA8tIM94tyazUg15QDmWxsExFp8VQr8j1/A2Mm0fKAVFekoEo0g0IO2a5ZZUZWzRR5lJrrNypcQaGX3erakxYD7JohKmqq8vrYxjNJ0boltjIknRN/H7jvH73CGymMqwBDEVPTmgzZCQFFyLYaIBNRVYHWAXhuyMdWjzMQOj+D50brc5JWZwv51clmUPLnyCO0d/gl1XXY0rSiAHfKnbv1MrZIynOayKxumBjGcMKqF+djiFPKsG22KDiAMQ+dBhB3Jk6ZgyIBIgO6tj/+xq599gAKzalQBYIKo+qudITOg9meGQUTaqJdA9jCKm1wZNgb8rnN15sSJu1UywaUcZO7gI/5DscyLdka0pitgl9Mmw/P72HWv243ccW4SmsGNc1nT4sSAxknk80jo9mdRoQ+akPvong7p3HWM7bSzyshBSxBZUEnLEff2AAz6rwl3mf3StNPOkR3PdrqH5B+h0DjezC1fKtQ43s8QKRp5G4/zMHkfhNPr1vr44mSRjbG/ScV+zX1j7WJmO3j5eypkIMHsfeFeBAA2D8nFkxMZB4wDthZg="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
