language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://metaclass.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "W7xlBVoSK87YtiDjFrepGsxbHbFiQocPpXC0tcC8VUW2AS2zDNXqSTa//08XqKhgKnioPGcV2o+48Rnouv3JhfLYo4HY3JVDCtlaW3kOxAWiYmuGRC28QPtDXcLeQD6MOmjUHKo9TgNDxSITPaGRqPTQAcHnX4Eie4F+tyRUNq1nMNC2DbYQr495V1r3pPpZZVgED9P490gVI2cmYiZ+88qjI1ng/xKLVsjuUVdnK7JKF+do6ad4BCQfo/p+MA8uW3122A6qf3D7wwJqelZq0kdiXCpf80Z9y9uqwsPV8RVXakT9gX5BAgPfZJG/aqJX2kTjsfXxQeY8LOR84JFdQpsSRPI6tjZWFL28hYZDDifVfWPfovJYfYjknSQ9QhbizdYThvJz6LS3QXoXXYu8n3B4NTqWVZ2PMaBg15DSDZ60QExqDVtnIW4MaJ+2rVFNDYhUh5YPU2UWq+KGdSG0uK4syhHANZYNFMr70yavD+OKWuJbIa8DDpL3s6Xgj7xiZKDzIzKUtJBG5ooxLhXm7FuuIQ9uGymFCdhgFTvH4if25lGTixTRmGGEaiOL6QUlKGcHn7LdPfo6ubUejfURxnjRNxrDw0F6b2ZdPBU2PcNHFFUjUT/2rflCvDDqBV2vdKgAQvo0ouRh2u2WEjFHz7m1SllRm8hYnkkFUr4byrU="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
