language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://metaclass.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "GUsGIXBgqOb5RjGf+71IO+EKcOkKz3GVesjD3A2bVG3afCeJHH9uL79sJbESGbaqQ7fURrViRSbcK7dngLX9XDwaef/nI1hbLMoWP/LyyRn2qLYuAWChBhcyoAka64HJ/QqpcwxhoC/1OQbBnYJxfub6uYWZSHgqndR7/mrT9r6hfOeh+xuqmwls9VD1dyJSqS+fhz8UnbL0JRWgpj2GRflNnNHNFRkoA+DpPBx8FwZUqiPnEL10AG3/XEmYlXQUj99hX7Uutxg7DhhrJ3eyzWiPLPueCyQSEU2mUAsNP2/avnXY+ZrvOTJGshnN6mGeIQn7kZhkLhRyuKCMG+gCb+3FXIdYSdsY2nkJhAuj1ZvyQlcSiNL4RSDehEcz0l6fUFZmYL9CF17T157nsUEp/2SGsCc9DUauaVwf1JF2bCyw3sS89TJbtazhMG1XcvTm05NvV+pnPBTsuzGGdGP2LzFUigDSvHf65NRNGi0rBfKlEZAadpwTKvhkzkPArIxWqokRL8/rMMD0hR4n/w6/BVPSMf3SQDyEq9czO5cnOWBeRzMhTX0BEGnGWS+84XNLutCaeYQv4apRSB2UwM0RC10NkOEeE6jxmQGFsuG27N0NgHG76ODGeg2H1l7xzEmKmhHBt/WpQVyGFIJHmOsMqFINquKgquZqUeioi7Hki6E="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
