language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://metaclass.pact.dius.com.au
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "NizwFpiz4e70hdfNNDXvrCWGzrfMGiRRKgpZnDqW2+eAMx86CIvkwZsrf/f8Ucqwmelrwwt+OmM5gdn2/NIUj1OZWglc36cSL1P0aWcxhYiBL8N4P2+j6SjoLfOnmDHk+rjh07+eHtQ2Gq7QF7rv3Y+7MSFh1S3NK8ZvqiY/oLhP3F9ZHhM/g1uvwY/CgLnFE9yYbk78154v1ULpfGtFWLKUGUKEc90xPll+gfMUtzw7ZYZF6PAFA1SH8okuqaeBVwrAiVo5Bt95PdFRSKZN/4FRlGSY/+JpZ0bc0qxC9E+lkNQcSJoLYB47g0McUxDiPGrvtIwis7cYdJqL7rDNBBCaHEY/6Q2zleddAV1dcbhsoh78/eMr3OhWwia3nYjkZnsx1+B4wy7AmQ/VO8iliWhovnE8XvB9UadXSZcBiiT/1ug1uL+qKibvnXNA0uqayrz0h1Ft7PcT1EwjUDruY7OvxwSsemnUxv9aVjh2e14PmMNxSzOtu1rXuVbh9kcbT/uGKkgXfB7GfeybkZD3hKiSn16dR/oZ38SWKSpSaB5Oje+fXSW7PKTAVKRelru6sjUVrAhCEZKP2pmSdo3DeYy1iLhNVqB66r5kOOFWKWAOvFtP7Q9PZKlGK0UgmIXlNvqDC26IuFZX8lvnjoSKF0pBlrDDBbyRNZ8FVFID7K4="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
